name: PR:4.x

on:
    pull_request:
        branches:
            - 4.x

concurrency:
    group: OCV-PR-Linux-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Ubuntu:
        runs-on: incredibuild-runner
        defaults:
            run:
                shell: bash
        env:
            CCACHE_DIR: "${{ github.workspace }}/.ccache"
            CCACHE_MAXSIZE: "8G"
            OPENCV_DOWNLOAD_PATH: "${{ github.workspace }}/binaries_cache"
            CMAKE_OPT: >-
                -DBUILD_DOCS=ON
                -DBUILD_EXAMPLES=ON
                -DOPENCV_ENABLE_NONFREE=ON
                -DWITH_IMGCODEC_GIF=ON
            WORKDIR: "${{ github.workspace }}"
            MAIN_BUILD_DIR: "${{ (github.event.repository.name != 'opencv_contrib') && 'build' || 'build-contrib' }}"
            OPENCV_FOR_THREADS_NUM: 4
            CMAKE_BUILD_PARALLEL_LEVEL: 4

        steps:
            - name: Checkout workflow repository
              uses: actions/checkout@v4
              with:
                  repository: opencv/ci-gha-workflow
                  ref: main

            - name: Checkout and merge OpenCV
              uses: ./checkout-and-merge
              with:
                  target_branch: "4.x"
                  author: "${{ github.event.pull_request.user.login }}"
                  source_branch: "${{ github.head_ref }}"
                  home: "${{ env.WORKDIR }}"
                  workdir: "${{ env.WORKDIR }}"

            - name: Create cache directories
              run: |
                  mkdir -p '${{ env.CCACHE_DIR }}'
                  mkdir -p '${{ env.OPENCV_DOWNLOAD_PATH }}'

            - name: Install build tools
              run: |
                  apt-get update
                  apt-get install -y cmake ninja-build

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Configure OpenCV
              working-directory: "${{ env.WORKDIR }}"
              run: |
                  echo "::group::Configure"
                  rm -rf build
                  mkdir -p build
                  cmake \
                    -S opencv \
                    -B build \
                    -G Ninja \
                    ${{ env.CMAKE_OPT }}
                  echo "::endgroup::"

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Build OpenCV
              working-directory: "${{ env.WORKDIR }}"
              run: |
                  set -x
                  echo "::group::Build"
                  /usr/bin/ib_console --standalone --build-cache-local-shared --build-cache-basedir=$PWD cmake --build build 2>&1 | tee build/log.txt
                  echo "::endgroup::"

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Check build warnings
              run: |
                  set +e
                  python3 ./scripts/warnings-handling.py \
                    '${{ env.WORKDIR }}/build/log.txt'
                  if [ $? -ne 0 ]; then
                    echo "WARNINGS=1" >> $GITHUB_ENV
                  fi

            - name: Configure OpenCV with contrib
              working-directory: "${{ env.WORKDIR }}"
              run: |
                  echo "::group::Configure"
                  rm -rf build-contrib
                  mkdir -p build-contrib
                  cmake \
                    -S opencv \
                    -B build-contrib \
                    -G Ninja \
                    -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules \
                    ${{ env.CMAKE_OPT }}
                  echo "::endgroup::"

            - name: Build OpenCV with contrib
              working-directory: "${{ env.WORKDIR }}"
              run: |
                  set -x
                  echo "::group::Build"
                  /usr/bin/ib_console --standalone --build-cache-local-shared --build-cache-basedir=$PWD cmake --build build-contrib 2>&1 | tee build-contrib/log.txt
                  echo "::endgroup::"

            - name: Check build-contrib warnings
              run: |
                  set +e
                  python3 ./scripts/warnings-handling.py \
                    '${{ env.WORKDIR }}/build-contrib/log.txt'
                  if [ $? -ne 0 ]; then
                    echo "WARNINGS=1" >> $GITHUB_ENV
                  fi

            - if: ${{ always() && env.WARNINGS == '1' }}
              name: Warnings check
              run: |
                  echo "::error Warnings have been found!"
                  exit 1
